### ISSUE TITLE
프로젝트 초기 셋팅

### ISSUE THREAD

**Issue by LeeOhHyung** [LeeOhHyung/android-weather-forecast#1]
# ISSUE

## 설명
`android-weather-forecast` application의 설계를 위한 초기 프로젝트 셋팅

## 작업 예정 사항
- [ ] Add rules to gitignore
- [ ] Android Project Settings - minSdk Version 23(Marshmallow)
- [ ] Add Issue, Pull Request Templates
- [ ] Define specification of android application

## 참고
[Weather API](https://openweathermap.org/api)
[Weather API Docs](https://openweathermap.org/current)
[Weather API - one call](https://openweathermap.org/api/one-call-api)

**Comment by laco-dev** [comment]
최근 목록에 떠있어서 인사드리로 왔어요.
토이 프로젝트를 진행하시는건가요?

**Comment by LeeOhHyung** [comment]
>최근 목록에 떠있어서 인사드리로 왔어요.
토이 프로젝트를 진행하시는건가요?

안녕하세요 라코님 ㅋㅋㅋ 오랜만입니다
네 맞아요 간단한 토이프로젝트 앱을 만들어볼려고 하고있어요.
부끄럽습니다 ㅠㅠ 간간히 들려주세요 ㅋㅋ

**Comment by laco-dev** [comment]
@LeeOhHyung 
넵. 슬랙으로 인사 다시 드릴게요~
