### ISSUE TITLE
Gradle Kotlin DSL

### ISSUE THREAD

**Issue by LeeOhHyung** [LeeOhHyung/android-weather-forecast#3]
# ISSUE

## 설명
`Gradle Groovy DSL`을 `Gradle Kotlin DSL`로 변경

## 작업 예정 사항
- [ ] Kotlin DSL 도입

## 스크린샷
<p>
    <img src="" width="300" />
</p>

## 참고
1. https://seansation-blog.tistory.com/7
2. https://proandroiddev.com/the-new-way-of-writing-build-gradle-with-kotlin-dsl-script-8523710c9670
3. https://kotlinlang.org/docs/reference/using-gradle.html
4. https://blog.naver.com/cutesboy3/221654207594
5. https://blog.naver.com/mym0404/221740631103

**Comment by laco-dev** [comment]
gradle kotlin은 buildSrc의 장점을 최대한 살릴 수 있는 구조입니다!
무궁무진한 활용이 가능하니,  찾아보시는것도 좋을 듯 하네요.
